lldb linux: add tests

diff --git a/linux/lldb/PKGBUILD b/linux/lldb/PKGBUILD
--- a/linux/lldb/PKGBUILD
+++ b/linux/lldb/PKGBUILD
@@ -88,12 +88,23 @@ build() {
     -DLLDB_ENABLE_LZMA=ON \
     -DLLVM_INCLUDE_EXAMPLES=OFF \
     -DLLVM_INCLUDE_BENCHMARKS=OFF \
-    -DLLVM_INCLUDE_TESTS=OFF \
     -DLLVM_APPEND_VC_REV=OFF \
     -DLLDB_VERSION_STRING="$(_llvm_pkgversion | _cmake_escape_semicolon)" \
+    $(
+      if [ -n "$CIDR_TEST_XML" ]; then
+        echo -DLLVM_INCLUDE_TESTS=ON -DCIDR_TEST_XML=$CIDR_TEST_XML
+      else
+        echo -DLLVM_INCLUDE_TESTS=OFF
+      fi
+    ) \
     "$srcdir/$_llvm_repository_name/llvm"
 
-  make
+  cmake --build . --verbose --target lldb lldb-argdumper lldb-dap lldb-server
+
+  if [ -n "$CIDR_TEST_XML" ]; then
+    # suppressing the exit code, as test results gonna be processed by teamcity at least before the tests go stable
+    cmake --build . --verbose --target check-lldb-xml ||:
+  fi
 
   # # Disable automatic installation of components that go into subpackages
   # sed -i '/\(clang\|lld\|lldb\)\/cmake_install.cmake/d' tools/cmake_install.cmake
